import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import App from './App.tsx';
import './index.css';

// Configure Amplify - will be generated by sandbox/pipeline
(async () => {
  try {
    const outputs = await import('../amplify_outputs.json');
    Amplify.configure(outputs.default || outputs);
  } catch (error) {
    console.warn('amplify_outputs.json not found. Backend will be configured after deployment.');
  }
})();

// Create React Query client
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
});

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <App />
    </QueryClientProvider>
  </StrictMode>,
);

