import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import App from './App.tsx';
import './index.css';

// Configure Amplify - will be generated by sandbox/pipeline
// Handle missing amplify_outputs.json gracefully for local dev
const configureAmplify = async () => {
  try {
    // Use fetch to avoid Vite import analysis issues
    const response = await fetch('/amplify_outputs.json');
    if (response.ok) {
      const outputs = await response.json();
      Amplify.configure(outputs);
    }
  } catch (error) {
    // File doesn't exist - that's okay for local dev
    // Backend will be configured after deployment
    console.warn('amplify_outputs.json not found. Run "npx ampx sandbox" for local backend.');
  }
};
configureAmplify();

// Create React Query client
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
});

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <App />
    </QueryClientProvider>
  </StrictMode>,
);
